function J = geom_jacobian(q)
% geom_jacobian   compute the geometric Jacobian

%% load physical parameters
phy_param;

%% from the model generator
J = [
    -al2*sin(q(1))*cos(q(2))-dl2*cos(q(1)), -al2*cos(q(1))*sin(q(2));...
     al2*cos(q(1))*cos(q(2))-dl2*sin(q(1)), -al2*sin(q(1))*sin(q(2));...
                                         0,           -al2*cos(q(2));...
                                         0,                -sin(q(1));...
                                         0,                 cos(q(1));...
                                         1,                         0;
];
